apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-processor-api
  name: location-processor-api
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    service: location-processor-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-processor-api
  name: location-processor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-processor-api
  template:
    metadata:
      labels:
        service: location-processor-api
    spec:
      containers:
        - image: themultitoolguy/locationprocessorservice:latest
          name: location-processor-container
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-processor-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: DB_PORT
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: db-proseessor-configmap
                  key: KAFKA_TOPIC
            - name: PYTHONUNBUFFERED
              value: '0'
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
